#!/data/data/com.termux/files/usr/bin/bash

# Açıksa kapat.
kill -9 $(pgrep -f "termux.x11") 2>/dev/null

# Pulseaudio'yu başlat
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

# X11 oturumu hazırla.
export XDG_RUNTIME_DIR=${TMPDIR}
termux-x11 :0 >/dev/null &

# Bekle.
sleep 3

# Termux-X11'i başlat.
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
sleep 1

# Pardus'u başlat (Aşağıda kullanici yazan yeri silip Pardus'ta koyduğunuz adı yazın.)
proot-distro login pardus --shared-tmp -- /bin/bash -c  'export PULSE_SERVER=127.0.0.1 && export XDG_RUNTIME_DIR=${TMPDIR} && su - kullanici -c "env DISPLAY=:0 LANG=tr_TR.UTF-8 && startxfce4"'

exit 0
